from telebot import TeleBot, types
from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton, ReplyKeyboardMarkup, KeyboardButton
def videos():
    vid1 = InlineKeyboardMarkup(row_width=4)
    vid1.add(InlineKeyboardButton("1 -- dars", callback_data="1_dars"), InlineKeyboardButton("2 -- dars", callback_data="2_dars"), InlineKeyboardButton("3 -- dars", callback_data="3_dars"), InlineKeyboardButton("4 -- dars", callback_data="4_dars"), InlineKeyboardButton("5 -- dars", callback_data="5_dars"), InlineKeyboardButton("6 -- dars", callback_data="6_dars"), InlineKeyboardButton("7 -- dars", callback_data="7_dars"), InlineKeyboardButton("8 -- dars", callback_data="8_dars"), InlineKeyboardButton("9 -- dars", callback_data="9_dars"), InlineKeyboardButton("10 -- dars", callback_data="10_dars"), InlineKeyboardButton("11 -- dars", callback_data="11_dars"), InlineKeyboardButton("12 -- dars", callback_data="12_dars"), InlineKeyboardButton("13 -- dars", callback_data="13_dars"), InlineKeyboardButton("14 -- dars", callback_data="14_dars"), InlineKeyboardButton("15 -- dars", callback_data="15_dars"), InlineKeyboardButton("16 -- dars", callback_data="16_dars"), InlineKeyboardButton("17 -- dars", callback_data="17_dars"), InlineKeyboardButton("18 -- dars", callback_data="18_dars"), InlineKeyboardButton("19 -- dars", callback_data="19_dars"), InlineKeyboardButton("20 -- dars", callback_data="20_dars"), InlineKeyboardButton("21 -- dars", callback_data="21_dars"), InlineKeyboardButton("22 -- dars", callback_data="22_dars"), InlineKeyboardButton("23 -- dars", callback_data="23_dars"), InlineKeyboardButton("24 -- dars", callback_data="24_dars"), InlineKeyboardButton("25 -- dars", callback_data="25_dars"), InlineKeyboardButton("26 -- dars", callback_data="26_dars"), InlineKeyboardButton("27 -- dars", callback_data="27_dars"), InlineKeyboardButton("28 -- dars", callback_data="28_dars"), InlineKeyboardButton("29 -- dars", callback_data="29_dars"), InlineKeyboardButton("30 -- dars", callback_data="30_dars"), InlineKeyboardButton("31 -- dars", callback_data="31_dars"), InlineKeyboardButton("32 -- dars", callback_data="32_dars"))
    return vid1
def menu():
    menu = InlineKeyboardMarkup(row_width=1)
    menu.add(InlineKeyboardButton("Matematika videolar", callback_data="matematika"), InlineKeyboardButton("Ibrat Farzandlari til oʻrganish", callback_data="ibrat"))
    return menu
  
